### ISSUE TITLE
compilation errors with vala 0.44.4

### ISSUE THREAD

**Issue by decathorpe** [elementary/applications-menu#210]
After upgrading vala from 0.44.3 to 0.44.4, these errors started to make the build fail:

```
dee-1.0.vapi:44.35-44.44: error: construct properties not supported for specified property type
		public Dee.Filter filter { get; construct; }
		                                ^^^^^^^^^^
dee-1.0.vapi:76.35-76.44: error: construct properties not supported for specified property type
		public Dee.ModelReader reader { construct; }
		                                ^^^^^^^^^^
```

and this warning:

```
(...)/src/Slingshot.vala:127.9-127.19: warning: `null' incompatible with return type `Wingpanel.Indicator'
        return null;
        ^^^^^^^^^^^
```
